<div class="touch">
		<div class="container">
			<div class="touch-main">
				<div class="col-md-4 touch-left">
					<h3>Get in touch</h3>
					<p>#8 Abatam close, Destiny layout, Emene Ind. Area(EIA), Enugu</p>
					<p>Call: +234 806.7740.725<p>
					<p>E-mail:<a href="mailto:example@email.com">koc.construction247@gmail.com</a>
				</div>
				<div class="col-md-4 touch-left">
					<h3>Services</h3>
					<p>Planning</p>
					<p>Building</p>
					<p>Delivery</p>
					<label></label>
				</div>
				<div class="col-md-4 touch-right">
					<h3>Social Media</h3>
					<ul>
						<li><a href="#"><span class="fb"> </span></a></li>
						<li><a href="#"><span class="twt"> </span></a></li>
						<li><a href="#"><span class="g"> </span></a></li>
						<li><a href="#"><span class="p"> </span></a></li>
						<li><a href="#"><span class="drb"> </span></a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-touch-->	
	<!--start-footer-->	
	<div class="footer">
		<div class="container">
			<div class="footer-text">
				<p>&copy; 2015 KCK. All rights reserved | Designed by <a href="#"> HarBay Inc.</a></p>
				<a href="#home" class="scroll"><img src="images/top-img.png" alt=""></a>
			</div>
		</div>
	</div>
	<!--End-footer-->