<div class="header" id="home">
		<div class="container">
			<div class="logo">
				<a href="index.php"><img src="images/logo.png" alt=""></a>  
			</div>
			<div class="quote">
				<a href="quote.php">GET A QUOTE</a>
			</div>
			<!--start-top-nav-->
			<nav class="top-nav">
				<ul class="top-nav">
					<li><a href="index.php"  class="active">Home</a></li>
					<li><a href="about.php">About us</a></li>
					<li><a href="404.php">Profiles</a></li>
					<li><a href="contact.php">Contact us</a></li>
				</ul>
					<a href="#" id="pull"><img src="images/menu-icon.png" title="menu" /></a>
			</nav>
			<div class="clearfix"> </div>
		</div>
	</div>